### PR TITLE
Remove dependency on antlr4-python-runtime

### LINKED ISSUE #43: antlr4-python3-runtime dependency makes statsforecast incompatible with other packages
## Problem
The current conda-forge recipe for statsforecast includes the dependency on `antlr4-python3-runtime>=4.11`. This prevents installation of `statsforecast` via conda alongside packages relying on older antlr4 versions (e.g., `omegaconf` requires `antlr4-python3-runtime==4.9.3`). 

https://github.com/conda-forge/statsforecast-feedstock/blob/main/recipe/meta.yaml#L31-L34

This, for example, makes it impossible to install `statsforecast>=1.5.0` alongside `pytorch-lightning[extra]` in a single environment since `pytorch-lightning` relies on `omegaconf` (https://github.com/Lightning-AI/pytorch-lightning/blob/master/requirements/pytorch/extra.txt#L6). 

This problem also make it impossible to install `statsforecast>=1.5.0` alongside `autogluon` that similarly depends on `omegaconf`. 

Note that installation via `pip` works and this problem only affects the conda install.

## Potential solution
This problem can be resolved by increasing the `fugue` lower bound to `fugue>=0.9.0`, which will make antr4 an optional dependency (https://github.com/fugue-project/fugue/issues/509).

### PR DESCRIPTION
**Pull request by shchur**
Fixes #43

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jmoralez — APPROVED** [review]
Thanks!

**Comment by jmoralez** [comment]
Oh I think we need to bump the build number to release this patch. Can you do it? Just have to set it to `1` here https://github.com/conda-forge/statsforecast-feedstock/blob/47d00672b81aaee2abbb9ca218713e9761d395da/recipe/meta.yaml#L3

**Comment by shchur** [comment]
Thanks for the quick review @jmoralez! Bumped the build number

**Comment by shchur** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
